include:
  - local: "/.gitlab-ci/utils.gitlab-ci.yml"
  - local: "/.gitlab-ci/test.gitlab-ci.yml"
  - local: "/.gitlab-ci/release.gitlab-ci.yml"

stages:
  - test
  - release

variables:
  DRY_CARGO_RELEASE: "false"
  CI_CARGO_PACKAGE: mavspec
  CI_RUST_DOC_FEATURES: rust,rust_gen,serde,unstable

# ---------------------------------------------------------
#                          Test
# ---------------------------------------------------------

test:validate:upstream:
  extends: .test:validate:upstream  # from: local: "/.gitlab-ci/test.gitlab-ci.yml"
  stage: test

test:validate:tags:
  extends: .test:validate:tags  # from: local: "/.gitlab-ci/test.gitlab-ci.yml"
  stage: test

test:build:docs:
  extends: .test:build:docs  # from: local: "/.gitlab-ci/test.gitlab-ci.yml"
  stage: test

test:test:
  extends: .test:test  # from: local: "/.gitlab-ci/test.gitlab-ci.yml"
  stage: test

# ---------------------------------------------------------
#                        Release
# ---------------------------------------------------------

release:publish:crates:deps:
  extends: .release:publish:crates  # from: local: "/.gitlab-ci/release.gitlab-ci.yml"
  stage: release
  needs:
    - test:validate:tags
    - test:build:docs
    - test:test
  parallel:
    matrix:
      - CI_CARGO_PACKAGE:
          - "mavspec_rust_gen"
          - "mavspec_rust_spec"

release:publish:crates:mavspec:
  extends: .release:publish:crates  # from: local: "/.gitlab-ci/release.gitlab-ci.yml"
  stage: release
  variables:
    CI_CARGO_PACKAGE: mavspec
  needs:
    - test:validate:tags
    - test:build:docs
    - test:test
    - release:publish:crates:deps

release:release:
  extends: .release:release  # from: local: "/.gitlab-ci/release.gitlab-ci.yml"
  stage: release
  needs:
    - release:publish:crates:mavspec
