//! # MAVLib
//!
//! This is toy implementation of a MAVLink-speaking library made to show capabilities of
//! `MAVCodeGen`.

#![warn(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]
#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;
// pub mod api;
pub mod errors;
pub mod io;

// /// # Autogenerated MAVLink protocol.
// ///
// /// Autogenerated MAVLink protocol entities.
// ///
// /// See [`dialects`](mavlink::dialects) for dialect implementations.
// pub mod mavlink {
//     include!("mavlink/mod.rs");
//     // include!(concat!(env!("OUT_DIR"), "/mavlink/mod.rs"));
// }
