//! # MAVLib
//!
//! This is toy implementation of a MAVLink-speaking library made to show capabilities of
//! `MAVCodeGen`.

#![warn(missing_docs)]
#![deny(rustdoc::broken_intra_doc_links)]
#![cfg_attr(not(feature = "std"), no_std)]

/// # Autogenerated `MAVLink` protocol.
///
/// Autogenerated `MAVlink` protocol entities.
pub mod mavlink {
    include!("mavlink/mod.rs");
    // include!(concat!(env!("OUT_DIR"), "/mavlink/mod.rs"));
}
