//! Utility functions exposed as library API.

use crate::rust::conventions::dialect_name;

/// Rust module name for a dialect as it generated by `MAVCodeGen`.  
pub fn dialect_module_name(name: &str) -> String {
    dialect_name(name.to_string())
}
