//! # MAVLink message

use crate::consts::MESSAGE_ID_V1_MAX;
use crate::payload::IntoPayload;
use crate::types::{ExtraCrc, MavLinkVersion, MessageId};

/// Generic MAVLink message specification.
///
/// [`MessageInfo`] implements this trait.
///
/// Messages generated by [MAVCodeGen](https://gitlab.com/mavka/libs/mavcodegen) also implement this trait.
pub trait MessageSpec {
    /// MAVLink message ID.
    ///
    /// In `MAVLink 2` message ID is a 24-bit unsigned integer stored as [`u32`].
    ///
    /// `MAVLink 1` supports only 8-bit message ID.
    ///
    /// # Links
    ///
    ///  - [MAVLink 2](https://mavlink.io/en/guide/mavlink_2.html)
    ///  - [MAVLink serialization](https://mavlink.io/en/guide/serialization.html)
    fn id(&self) -> MessageId;

    /// Minimum supported MAVLink protocol version.
    ///
    /// Messages supporting both `MAVLink 1` and `MAVLink 2` will return [`MavLinkVersion::V1`].
    ///
    /// Messages which make sense only in `MAVLink 2` will return [`MavLinkVersion::V2`],
    fn min_supported_mavlink_version(&self) -> MavLinkVersion;

    /// Message `EXTRA_CRC` calculated from message XML definition.
    ///
    /// CRC for message name and key message fields to detect incompatible changes in
    /// message definition.
    ///
    /// See: [CRC_EXTRA calculation](https://mavlink.io/en/guide/serialization.html#crc_extra) in
    /// MAVLink docs.
    fn extra_crc(&self) -> ExtraCrc;
}

/// MAVLink message implementation.
///
/// Concrete MAVLink message that knows its specs through [`MessageSpec`] and allows to decode itself into
/// [`Payload`](crate::payload::Payload) via [`IntoPayload`].
pub trait MessageImpl: MessageSpec + IntoPayload {}

/// Generic information about MAVLink message.
///
/// Used in dialects to provide information required for message verification and processing.
#[derive(Copy, Clone, Debug)]
pub struct MessageInfo {
    id: MessageId,
    min_supported_mavlink_version: MavLinkVersion,
    extra_crc: ExtraCrc,
}

impl MessageSpec for MessageInfo {
    /// MAVLink message ID.
    ///
    /// See: [`MessageSpec::id`].
    #[inline]
    fn id(&self) -> MessageId {
        self.id
    }

    /// Minimum supported MAVLink protocol version.
    ///
    /// See: [`MessageSpec::min_supported_mavlink_version`].
    #[inline]
    fn min_supported_mavlink_version(&self) -> MavLinkVersion {
        self.min_supported_mavlink_version
    }

    /// Message `EXTRA_CRC` calculated from message XML definition.
    ///
    /// See: [`MessageSpec::extra_crc`].
    #[inline]
    fn extra_crc(&self) -> ExtraCrc {
        self.extra_crc
    }
}

impl MessageInfo {
    /// Default constructor.
    ///
    /// Sets `min_supported_mavlink_version` to [`MavLinkVersion::V2`] if message `id` greater
    /// than [`u8::MAX`]. The latter means it can't be fitted into `MAVLink 1` packet. Otherwise
    /// sets to [`MavLinkVersion::V1`].
    pub const fn new(id: MessageId, extra_crc: ExtraCrc) -> Self {
        // Force `MAVLink 2` as minimum protocol version if `id` can't be represented as `u8`
        let min_supported_mavlink_version = if id > MESSAGE_ID_V1_MAX {
            MavLinkVersion::V2
        } else {
            MavLinkVersion::V1
        };

        Self {
            id,
            min_supported_mavlink_version,
            extra_crc,
        }
    }
}
